export default interface ParsingType {
  cid: string,
  dtParams: any,
  duration: string,
  focusOn: string,
  fullTitle: string,
  imgTag: string,
  index: number,
  isNoStoreWatchHistory: string,
  itemType: string,
  lid: string,
  listKey: string,
  page: number,
  pic: string,
  picVertial: string,
  playTitle: string,
  publishDate: string,
  refreshPage: string,
  title: string,
  vid: string,
}
